"""
email_report.py
---------------
Sends the HTML report (with the Excel reports attached) by email.

Safety:
  * Email is OFF unless settings.yaml -> email.enabled is true
    AND an app password is available.
  * The Gmail App Password is read from the .env file (key EMAIL_APP_PASSWORD)
    or the environment variable of the same name.  It is never stored in code.

To enable:
  1. Create a Gmail App Password (Google account -> Security -> App passwords).
  2. Put it in a file named .env in the project root:
         EMAIL_APP_PASSWORD=your16charapppassword
  3. Set email.enabled: true in config/settings.yaml
"""

import os
import re
import smtplib
import mimetypes
from html import escape
from email.message import EmailMessage

from utilities import config_loader
from utilities.logger import get_logger

log = get_logger()

# branding image cid -> the CSS class used for that <img> in the HTML report
_BRAND_IMAGES = [("logo", "company_logo", "logo"),
                 ("author", "author_image", "avatar")]

# every header cell carries border:0 inline so the report's global
# `td { border-bottom:1px solid #e6ecf2 }` rule cannot paint faint lines in it
_TD0 = "border:0;border-bottom:0;padding:0;"


def _branding_cfg():
    return (config_loader.get_settings().get("reporting", {}) or {}).get(
        "branding", {}) or {}


def _branding_image_files():
    """Return [(cid, css_class, abs_path), ...] for branding images that exist."""
    branding = _branding_cfg()
    out = []
    for cid, key, css_class in _BRAND_IMAGES:
        path = branding.get(key)
        if not path:
            continue
        abs_path = path if os.path.isabs(path) else config_loader.abs_path(path)
        if os.path.exists(abs_path):
            out.append((cid, css_class, abs_path))
    return out


def _email_header_html(images, gen_on, gen_by):
    """
    Fully INLINE-STYLED header for email: blue background (solid + theme
    gradient), logo + title/company/dates on the left, photo + name + role
    right-aligned. Every <td> has border:0 so the report's global td border rule
    cannot draw faint white lines. Images use cid: references.
    """
    brand = _branding_cfg()
    have = {cid for cid, _c, _p in images}
    company = escape(brand.get("company_name", ""))
    author_name = escape(brand.get("author_name", "") or "")
    author_role = escape(brand.get("author_role", "Report Author"))

    logo_img = ('<img src="cid:logo" alt="logo" '
                'style="height:52px;max-width:180px;background:#ffffff;'
                'border-radius:8px;padding:5px;display:block;border:0;">'
                if "logo" in have else "")
    author_img = ('<img src="cid:author" alt="author" width="64" height="64" '
                  'style="height:64px;width:64px;border-radius:50%;object-fit:cover;'
                  'border:2px solid #ffffff;display:inline-block;">'
                  if "author" in have else "")
    company_html = (f'<div style="font-size:15px;font-weight:700;color:#ffd27d;'
                    f'margin:4px 0 0;letter-spacing:.3px;">{company}</div>'
                    if company else "")

    return f"""<header style="background-color:#1b3a6b;background-image:linear-gradient(135deg,#102a43,#243b74);color:#ffffff;padding:22px 32px;font-family:Segoe UI,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;background:transparent;">
    <tr>
      <td align="left" valign="middle" style="{_TD0}vertical-align:middle;">
        <table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:transparent;">
          <tr>
            <td valign="middle" style="{_TD0}vertical-align:middle;padding-right:18px;">{logo_img}</td>
            <td valign="middle" style="{_TD0}vertical-align:middle;">
              <div style="margin:0;font-size:22px;font-weight:700;color:#ffffff;">Banking ETL Automation &ndash; Test Execution Report</div>
              {company_html}
              <div style="margin:6px 0 0;color:#c3d0e8;font-size:13px;">Generated on : {escape(gen_on)}</div>
              <div style="margin:2px 0 0;color:#c3d0e8;font-size:13px;">Generated by : {escape(gen_by)}</div>
            </td>
          </tr>
        </table>
      </td>
      <td align="right" valign="middle" style="{_TD0}vertical-align:middle;padding-left:24px;">
        <div style="text-align:right;">
          {author_img}
          <div style="font-size:13px;font-weight:600;margin-top:6px;color:#ffffff;">{author_name}</div>
          <div style="font-size:11px;color:#c3d0e8;">{author_role}</div>
        </div>
      </td>
    </tr>
  </table>
</header>"""


def _rewrite_header_for_email(html, images):
    """Swap the whole <header>...</header> for the inline-styled email version."""
    m_on = re.search(r'Generated on\s*:\s*([^<]*)', html)
    m_by = re.search(r'Generated by\s*:\s*([^<]*)', html)
    gen_on = m_on.group(1).strip() if m_on else ""
    gen_by = m_by.group(1).strip() if m_by else ""
    new_header = _email_header_html(images, gen_on, gen_by)
    return re.sub(r"<header>.*?</header>", lambda _m: new_header, html,
                  count=1, flags=re.DOTALL)


def _read_env_password():
    """Get EMAIL_APP_PASSWORD from the environment or the .env file."""
    if os.environ.get("EMAIL_APP_PASSWORD"):
        return os.environ["EMAIL_APP_PASSWORD"].strip()

    env_path = config_loader.abs_path(".env")
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("EMAIL_APP_PASSWORD=") and not line.startswith("#"):
                    return line.split("=", 1)[1].strip()
    return None


def send_report(html_path, attachments=None):
    """
    Send the report by email.
    Returns True if sent, False if skipped/failed (never raises).
    """
    cfg = config_loader.get_settings()["email"]
    attachments = attachments or []

    if not cfg.get("enabled", False):
        log.info("Email skipped (email.enabled is false in settings.yaml).")
        return False

    password = _read_env_password()
    if not password:
        log.warning("Email skipped (no EMAIL_APP_PASSWORD found in .env / environment).")
        return False

    try:
        with open(html_path, "r", encoding="utf-8") as f:
            body = f.read()

        # rebuild the header inline (blue background, right-aligned author, no
        # stray border lines) so it renders correctly in email clients
        brand_images = _branding_image_files()
        body = _rewrite_header_for_email(body, brand_images)

        brand = _branding_cfg()
        plain = "\n".join(x for x in [
            brand.get("company_name", ""),
            f"{brand.get('author_name', '')} - {brand.get('author_role', '')}".strip(" -"),
            "",
            "This report is best viewed as HTML. "
            "See the attached Excel reports for details.",
        ] if x is not None)

        msg = EmailMessage()
        msg["Subject"] = cfg["subject"]
        msg["From"] = cfg["sender"]
        msg["To"] = ", ".join(cfg["recipients"])
        msg.set_content(plain)
        msg.add_alternative(body, subtype="html")

        # attach branding images inline (Content-ID) to the HTML alternative part
        html_part = msg.get_payload()[1]
        for cid, _css, abs_path in brand_images:
            with open(abs_path, "rb") as fh:
                data = fh.read()
            subtype = (mimetypes.guess_type(abs_path)[0] or "image/png").split("/")[-1]
            html_part.add_related(data, maintype="image", subtype=subtype,
                                  cid=f"<{cid}>")

        for path in attachments:
            if path and os.path.exists(path):
                with open(path, "rb") as fh:
                    data = fh.read()
                fname = os.path.basename(path)
                msg.add_attachment(data, maintype="application",
                                   subtype="octet-stream", filename=fname)

        with smtplib.SMTP(cfg["smtp_server"], cfg["smtp_port"], timeout=30) as server:
            server.starttls()
            server.login(cfg["sender"], password)
            server.send_message(msg)

        log.info(f"Email sent to {msg['To']}.")
        return True
    except Exception as e:
        log.error(f"Email failed: {e}")
        return False
