-- =====================================================================
-- INSERT golden data into dbo.SRC_Branches
-- Golden snapshot of source data  |  database: Bank_Source
-- Generated: 2026-07-17 00:34:25
-- Generated by GoldenTestData/generate_golden_data.py (READ-ONLY snapshot)
-- =====================================================================
USE Bank_Source;
GO

INSERT INTO dbo.SRC_Branches ([BranchID], [BranchCode], [BranchName], [City], [StateName], [Country], [ManagerName], [CreatedDate], [UpdatedDate]) VALUES (101, 'BR001', 'Delhi Central Branch', 'Delhi', 'UP', 'India', 'Suresh Malhotra', '2022-01-01 09:00:00.000', NULL);
INSERT INTO dbo.SRC_Branches ([BranchID], [BranchCode], [BranchName], [City], [StateName], [Country], [ManagerName], [CreatedDate], [UpdatedDate]) VALUES (102, 'BR002', 'Mumbai Andheri Branch', 'Mumbai', 'Maharashtra', 'India', 'Anita Desai', '2022-01-05 09:00:00.000', NULL);
INSERT INTO dbo.SRC_Branches ([BranchID], [BranchCode], [BranchName], [City], [StateName], [Country], [ManagerName], [CreatedDate], [UpdatedDate]) VALUES (103, 'BR003', 'Kolkata Salt Lake Branch', 'Kolkata', 'West Bengal', 'India', 'Subhash Bose', '2022-01-10 09:00:00.000', NULL);
INSERT INTO dbo.SRC_Branches ([BranchID], [BranchCode], [BranchName], [City], [StateName], [Country], [ManagerName], [CreatedDate], [UpdatedDate]) VALUES (104, 'BR004', 'Hyderabad Jubilee Branch', 'Hyderabad', 'Telangana', 'India', 'Ramesh Rao', '2022-01-15 09:00:00.000', NULL);
INSERT INTO dbo.SRC_Branches ([BranchID], [BranchCode], [BranchName], [City], [StateName], [Country], [ManagerName], [CreatedDate], [UpdatedDate]) VALUES (105, 'BR005', 'Bengaluru Indiranagar', 'Bengaluru', 'Karnataka', 'India', 'Meera Iyer', '2022-01-20 09:00:00.000', NULL);
GO
