-- =====================================================================
-- INSERT golden data into dbo.SRC_Accounts
-- Golden snapshot of source data  |  database: Bank_Source
-- Generated: 2026-07-17 00:34:25
-- Generated by GoldenTestData/generate_golden_data.py (READ-ONLY snapshot)
-- =====================================================================
USE Bank_Source;
GO

INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1001, 'AC0000001001', 1, 'Savings', '2023-01-11', NULL, 'Active', 25000.00, 'INR', '2023-01-11 09:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1002, 'AC0000001002', 2, 'Current', '2023-01-23', NULL, 'Active', 100.00, 'INR', '2023-01-13 10:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1003, 'AC0000001003', 3, 'Savings', '2023-01-16', NULL, 'Active', 15000.75, 'INR', '2023-01-16 11:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1004, 'AC0000001004', 4, 'Salary', '2023-02-02', NULL, 'Active', 55000.00, 'INR', '2023-02-02 12:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1005, 'AC0000001005', 5, 'Savings', '2023-02-06', NULL, 'Active', 125000.25, 'INR', '2023-02-06 13:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1006, 'AC0000001006', 6, 'Current', '2023-02-11', NULL, 'Active', 300000.00, 'INR', '2023-02-11 14:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1007, 'AC0000001007', 7, 'Savings', '2023-03-03', NULL, 'Active', 48000.00, 'INR', '2023-03-03 15:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1008, 'AC0000001008', 8, 'Salary', '2023-03-08', NULL, 'Active', 72000.00, 'INR', '2023-03-08 16:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1009, 'AC0000001009', 9, 'Savings', '2023-03-12', NULL, 'Active', 9800.00, 'INR', '2023-03-12 17:30:00.000', NULL);
INSERT INTO dbo.SRC_Accounts ([AccountID], [AccountNumber], [CustomerID], [AccountType], [OpenDate], [CloseDate], [Status], [Balance], [CurrencyCode], [CreatedDate], [UpdatedDate]) VALUES (1010, 'AC0000001010', 10, 'Current', '2023-03-21', NULL, 'Active', 215000.00, 'INR', '2023-03-21 18:30:00.000', NULL);
GO
