"""
agents/agent_4_test_data.py   -   STEP 4
========================================
AI Agent: generate TEST DATA for the four SOURCE tables + INSERT scripts.

This agent ONLY WRITES .sql script files - it never connects to the database to
run DELETE / INSERT / EXEC. Executing the scripts is your explicit action (run
them in SSMS or with sqlcmd), exactly like tests/test_00_prerequisite.py.

It produces realistic banking rows PLUS deliberately "bad" rows so the pipeline's
Layer-2 cleaning / rejection logic actually gets exercised (bad email, negative
amount, un-trimmed text, unknown status / gender / transaction type, lower-case
values that should be standardised, apostrophes to test SQL escaping).

Output (INSERT scripts only - NEVER executed here; running them is your action,
just like tests/test_00_prerequisite.py runs the reset script):

    agents/output/testdata/01_SRC_Branches.sql
    agents/output/testdata/02_SRC_Customers.sql
    agents/output/testdata/03_SRC_Accounts.sql
    agents/output/testdata/04_SRC_Transactions.sql
    agents/output/testdata/insert_all_source_testdata.sql   (reset + insert + load)

Rows are written in FK-safe order (Branches -> Customers -> Accounts ->
Transactions). The SQL-literal / INSERT-block approach mirrors
GoldenTestData/generate_golden_data.py.

Run:
    python -m agents.agent_4_test_data
"""

import os
import datetime
import decimal

from utilities import config_loader
from utilities.logger import get_logger
from agents import base

log = get_logger()

SOURCE_LOGICAL_DB = "source"

# DELETE order: children before parents, warehouse first -> source last.
DELETE_ORDER = [
    ("dwh", ["dbo.FactTransaction", "dbo.DimAccount_Type1",
             "dbo.DimBranch_Type2", "dbo.DimCustomer_Type2"]),
    ("staging", ["dbo.STG_Transactions", "dbo.STG_Accounts",
                 "dbo.STG_Customers", "dbo.STG_Branches"]),
    ("prestaging", ["dbo.PS_Transactions", "dbo.PS_Accounts",
                    "dbo.PS_Customers", "dbo.PS_Branches"]),
    ("source", ["dbo.SRC_Transactions", "dbo.SRC_Accounts",
                "dbo.SRC_Customers", "dbo.SRC_Branches"]),
]
LOAD_PROC_ORDER = [
    ("Layer 1 : Source -> PreStaging", "prestaging",
     ["dbo.usp_Load_PS_Branches", "dbo.usp_Load_PS_Customers",
      "dbo.usp_Load_PS_Accounts", "dbo.usp_Load_PS_Transactions"]),
    ("Layer 2 : PreStaging -> Staging", "staging",
     ["dbo.usp_Load_STG_Branches", "dbo.usp_Load_STG_Customers",
      "dbo.usp_Load_STG_Accounts", "dbo.usp_Load_STG_Transactions"]),
    ("Layer 3 : Staging -> DWH", "dwh",
     ["dbo.usp_Load_DimBranch_Type2", "dbo.usp_Load_DimCustomer_Type2",
      "dbo.usp_Load_DimAccount_Type1", "dbo.usp_Load_FactTransaction"]),
]

D = datetime.date  # shorthand for the dataset below


# --------------------------------------------------------------------------
# SQL literal helpers (same behaviour as GoldenTestData/generate_golden_data.py)
# --------------------------------------------------------------------------
def sql_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, decimal.Decimal)):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, datetime.datetime):
        return "'" + value.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + "'"
    if isinstance(value, datetime.date):
        return "'" + value.strftime("%Y-%m-%d") + "'"
    return "'" + str(value).replace("'", "''") + "'"


def build_insert_block(full_table, columns, rows):
    col_list = ", ".join(f"[{c}]" for c in columns)
    lines = []
    for row in rows:
        note = row.get("_note")
        values = ", ".join(sql_value(row[c]) for c in columns)
        line = f"INSERT INTO {full_table} ({col_list}) VALUES ({values});"
        if note:
            line += f"  -- {note}"
        lines.append(line)
    return "\n".join(lines)


def _header(title):
    db_name = config_loader.resolve_database(SOURCE_LOGICAL_DB)
    return (
        "-- =====================================================================\n"
        f"-- {title}\n"
        f"-- Synthetic TEST DATA (positive + negative)  |  database: {db_name}\n"
        "-- Generated by agents/agent_4_test_data.py (script only - not executed)\n"
        "-- '-- NEGATIVE:' rows deliberately violate a Layer-2 rule so the\n"
        "-- pipeline's cleaning / rejection logic is exercised.\n"
        "-- =====================================================================\n"
    )


# --------------------------------------------------------------------------
# the deterministic dataset (FK-safe). Each table: (full_table, columns, rows)
# --------------------------------------------------------------------------
def _dataset():
    branches_cols = ["BranchID", "BranchCode", "BranchName", "City",
                     "StateName", "Country", "ManagerName"]
    branches = [
        {"BranchID": 1, "BranchCode": "BR001", "BranchName": "Downtown Branch",
         "City": "Mumbai", "StateName": "Maharashtra", "Country": "India",
         "ManagerName": "Amit Shah"},
        {"BranchID": 2, "BranchCode": "BR002", "BranchName": "  City Center  ",
         "City": "Delhi", "StateName": "Delhi", "Country": "India",
         "ManagerName": "Ravi Kumar", "_note": "NEGATIVE: BranchName has leading/trailing spaces"},
        {"BranchID": 3, "BranchCode": "BR003", "BranchName": "Airport Branch",
         "City": "Bengaluru", "StateName": "Karnataka", "Country": "india",
         "ManagerName": "Neha Rao", "_note": "lower-case country to be standardised"},
        {"BranchID": 4, "BranchCode": "BR004", "BranchName": "Tech Park",
         "City": "Hyderabad", "StateName": "Telangana", "Country": "India",
         "ManagerName": "Sana Khan"},
        {"BranchID": 5, "BranchCode": "BR005", "BranchName": "Lake View",
         "City": "Pune", "StateName": "Maharashtra", "Country": "India",
         "ManagerName": "John D'Souza", "_note": "apostrophe tests SQL escaping"},
    ]

    customers_cols = ["CustomerID", "CustomerCode", "CustomerName", "DOB",
                      "Gender", "Email", "Phone", "AddressLine", "City",
                      "StateName", "Country"]
    customers = [
        {"CustomerID": 1, "CustomerCode": "CU001", "CustomerName": "Ramesh Iyer",
         "DOB": D(1985, 3, 12), "Gender": "MALE", "Email": "ramesh.iyer@example.com",
         "Phone": "9800000001", "AddressLine": "12 MG Road", "City": "Mumbai",
         "StateName": "Maharashtra", "Country": "India"},
        {"CustomerID": 2, "CustomerCode": "CU002", "CustomerName": "  Sita Verma  ",
         "DOB": D(1990, 7, 1), "Gender": "female", "Email": "sita.verma@example.com",
         "Phone": "9800000002", "AddressLine": "5 Park Street", "City": "Delhi",
         "StateName": "Delhi", "Country": "India",
         "_note": "NEGATIVE: name has spaces; gender lower-case to be standardised"},
        {"CustomerID": 3, "CustomerCode": "CU003", "CustomerName": "Arjun Bad-Email",
         "DOB": D(1978, 11, 23), "Gender": "MALE", "Email": "not-an-email",
         "Phone": "9800000003", "AddressLine": "9 Lake Rd", "City": "Bengaluru",
         "StateName": "Karnataka", "Country": "India",
         "_note": "NEGATIVE: Email is not a valid email address"},
        {"CustomerID": 4, "CustomerCode": "CU004", "CustomerName": "Priya Nair",
         "DOB": D(1995, 2, 14), "Gender": "FEMALE", "Email": "priya.nair@example.com",
         "Phone": "9800000004", "AddressLine": "77 Hill View", "City": "Hyderabad",
         "StateName": "Telangana", "Country": "India"},
        {"CustomerID": 5, "CustomerCode": "CU005", "CustomerName": "O'Brien Singh",
         "DOB": D(1982, 9, 30), "Gender": "OTHER", "Email": "obrien.singh@example.com",
         "Phone": "9800000005", "AddressLine": "3 River Walk", "City": "Pune",
         "StateName": "Maharashtra", "Country": "India",
         "_note": "apostrophe in name tests SQL escaping"},
        {"CustomerID": 6, "CustomerCode": "CU006", "CustomerName": "Kiran Xample",
         "DOB": D(2000, 1, 1), "Gender": "X", "Email": "kiran.x@example.com",
         "Phone": "9800000006", "AddressLine": "1 First St", "City": "Chennai",
         "StateName": "Tamil Nadu", "Country": "India",
         "_note": "NEGATIVE: Gender 'X' is not in the allowed set"},
    ]

    accounts_cols = ["AccountID", "AccountNumber", "CustomerID", "AccountType",
                     "OpenDate", "CloseDate", "Status", "Balance", "CurrencyCode"]
    accounts = [
        {"AccountID": 1001, "AccountNumber": "AC00000001", "CustomerID": 1,
         "AccountType": "SAVINGS", "OpenDate": D(2020, 1, 15), "CloseDate": None,
         "Status": "ACTIVE", "Balance": decimal.Decimal("15000.50"),
         "CurrencyCode": "INR"},
        {"AccountID": 1002, "AccountNumber": "AC00000002", "CustomerID": 2,
         "AccountType": "CURRENT", "OpenDate": D(2019, 6, 1), "CloseDate": None,
         "Status": "active", "Balance": decimal.Decimal("2500.00"),
         "CurrencyCode": "INR", "_note": "lower-case status to be standardised"},
        {"AccountID": 1003, "AccountNumber": "AC00000003", "CustomerID": 3,
         "AccountType": "SAVINGS", "OpenDate": D(2021, 3, 20), "CloseDate": None,
         "Status": "FROZEN", "Balance": decimal.Decimal("100.00"),
         "CurrencyCode": "US",
         "_note": "NEGATIVE: unknown Status + CurrencyCode not 3 letters"},
        {"AccountID": 1004, "AccountNumber": "AC00000004", "CustomerID": 4,
         "AccountType": "SAVINGS", "OpenDate": D(2018, 12, 31),
         "CloseDate": D(2022, 1, 1), "Status": "CLOSED",
         "Balance": decimal.Decimal("0.00"), "CurrencyCode": "INR"},
        {"AccountID": 1005, "AccountNumber": "  AC00000005  ", "CustomerID": 5,
         "AccountType": "CURRENT", "OpenDate": D(2022, 7, 7), "CloseDate": None,
         "Status": "ACTIVE", "Balance": decimal.Decimal("9999.99"),
         "CurrencyCode": "INR",
         "_note": "NEGATIVE: AccountNumber has leading/trailing spaces"},
        {"AccountID": 1006, "AccountNumber": "AC00000006", "CustomerID": 6,
         "AccountType": "DORMANT", "OpenDate": D(2017, 5, 5), "CloseDate": None,
         "Status": "DORMANT", "Balance": decimal.Decimal("500.00"),
         "CurrencyCode": "usd", "_note": "lower-case currency to be standardised"},
    ]

    transactions_cols = ["TransactionID", "TransactionNumber", "AccountID",
                         "BranchID", "TransactionDate", "TransactionType",
                         "Amount", "CurrencyCode", "Description"]
    transactions = [
        {"TransactionID": 5001, "TransactionNumber": "TXN00000001", "AccountID": 1001,
         "BranchID": 1, "TransactionDate": D(2023, 1, 10), "TransactionType": "CREDIT",
         "Amount": decimal.Decimal("5000.00"), "CurrencyCode": "INR",
         "Description": "Salary credit"},
        {"TransactionID": 5002, "TransactionNumber": "TXN00000002", "AccountID": 1001,
         "BranchID": 1, "TransactionDate": D(2023, 1, 15), "TransactionType": "debit",
         "Amount": decimal.Decimal("1200.00"), "CurrencyCode": "INR",
         "Description": "ATM withdrawal", "_note": "lower-case type to be standardised"},
        {"TransactionID": 5003, "TransactionNumber": "TXN00000003", "AccountID": 1002,
         "BranchID": 2, "TransactionDate": D(2023, 2, 1), "TransactionType": "TRANSFER",
         "Amount": decimal.Decimal("300.00"), "CurrencyCode": "INR",
         "Description": "Fund transfer"},
        {"TransactionID": 5004, "TransactionNumber": "TXN00000004", "AccountID": 1003,
         "BranchID": 3, "TransactionDate": D(2023, 2, 5), "TransactionType": "REFUND",
         "Amount": decimal.Decimal("250.00"), "CurrencyCode": "INR",
         "Description": "Refund", "_note": "NEGATIVE: unknown TransactionType"},
        {"TransactionID": 5005, "TransactionNumber": "TXN00000005", "AccountID": 1004,
         "BranchID": 4, "TransactionDate": D(2023, 3, 1), "TransactionType": "DEPOSIT",
         "Amount": decimal.Decimal("-100.00"), "CurrencyCode": "INR",
         "Description": "Cash deposit", "_note": "NEGATIVE: Amount is negative"},
        {"TransactionID": 5006, "TransactionNumber": "TXN00000006", "AccountID": 1005,
         "BranchID": 5, "TransactionDate": D(2023, 3, 10), "TransactionType": "WITHDRAWAL",
         "Amount": decimal.Decimal("800.00"), "CurrencyCode": "INR",
         "Description": "Cash withdrawal"},
        {"TransactionID": 5007, "TransactionNumber": "TXN00000007", "AccountID": 1006,
         "BranchID": 1, "TransactionDate": D(2023, 4, 1), "TransactionType": "CREDIT",
         "Amount": decimal.Decimal("2000.00"), "CurrencyCode": "INR",
         "Description": "Interest credit"},
        {"TransactionID": 5008, "TransactionNumber": "TXN00000008", "AccountID": 1001,
         "BranchID": 2, "TransactionDate": D(2023, 4, 15), "TransactionType": "DEBIT",
         "Amount": decimal.Decimal("50.00"), "CurrencyCode": "INR",
         "Description": "Service fee's", "_note": "apostrophe tests SQL escaping"},
    ]

    return [
        ("01", "dbo.SRC_Branches", branches_cols, branches),
        ("02", "dbo.SRC_Customers", customers_cols, customers),
        ("03", "dbo.SRC_Accounts", accounts_cols, accounts),
        ("04", "dbo.SRC_Transactions", transactions_cols, transactions),
    ]


# --------------------------------------------------------------------------
# optional AI enrichment - extra realistic rows for FK-free tables only
# --------------------------------------------------------------------------
def _maybe_ai_extra(full_table, columns, start_id, id_col, code_col, code_prefix):
    """
    Ask Claude for a few extra POSITIVE rows for Branches/Customers (no FK deps),
    so we don't risk breaking referential integrity. Returns a list of row dicts
    with fresh IDs. Never raises; returns [] without a key or on any error.
    """
    if not base.have_api_key():
        return []
    try:
        from pydantic import BaseModel

        class Row(BaseModel):
            values: dict

        class Rows(BaseModel):
            rows: list[Row]

        system = (
            "You generate realistic, valid banking test data. Return 3 extra "
            f"rows for {full_table}. Use ONLY these columns: {', '.join(columns)}. "
            "All values must be valid (proper email, standardised upper-case where "
            "relevant, trimmed text). Dates as YYYY-MM-DD strings."
        )
        user = (f"Give 3 new valid rows. Use {id_col} starting at {start_id} "
                f"(increment by 1) and unique {code_col} like {code_prefix}xxx.")
        result = base.ask_claude_json(system, user, Rows, max_tokens=1500)
        out = []
        for i, r in enumerate(result.rows):
            row = {c: r.values.get(c) for c in columns}
            row[id_col] = start_id + i  # trust our IDs, not the model's
            row["_note"] = "AI-generated positive row"
            out.append(row)
        log.info(f"[agent_4] AI added {len(out)} rows to {full_table}")
        return out
    except Exception as exc:
        log.warning(f"[agent_4] AI extra rows skipped for {full_table} ({exc})")
        return []


# --------------------------------------------------------------------------
# writers
# --------------------------------------------------------------------------
def _write_per_table(out_dir, dataset):
    db_name = config_loader.resolve_database(SOURCE_LOGICAL_DB)
    paths = []
    for prefix, full_table, columns, rows in dataset:
        body = build_insert_block(full_table, columns, rows)
        text = (
            _header(f"INSERT test data into {full_table}")
            + f"USE {db_name};\nGO\n\n" + body + "\nGO\n"
        )
        path = os.path.join(out_dir, f"{prefix}_{full_table.split('.')[-1]}.sql")
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        paths.append(path)
        log.info(f"[agent_4] wrote {os.path.basename(path)} ({len(rows)} rows)")
    return paths


def _write_combined(out_dir, dataset):
    """One runnable script: reset all layers -> insert source test data -> load."""
    db_of = config_loader.resolve_database
    parts = [_header("FULL RESET + LOAD using synthetic TEST DATA")]
    parts.append("SET XACT_ABORT ON;")
    parts.append("SET NOCOUNT ON;")
    parts.append("GO\n")

    parts.append("-- STEP 1 : DELETE all data from all 4 layers (children first)")
    for logical, tables in DELETE_ORDER:
        parts.append(f"USE [{db_of(logical)}];")
        parts.append("GO")
        for t in tables:
            parts.append(f"DELETE FROM {t};")
        parts.append("GO\n")

    parts.append("-- STEP 2 : INSERT synthetic test data into SOURCE (parents first)")
    parts.append(f"USE [{db_of(SOURCE_LOGICAL_DB)}];")
    parts.append("GO")
    for _prefix, full_table, columns, rows in dataset:
        parts.append(f"-- ---- {full_table} ({len(rows)} rows) ----")
        parts.append(build_insert_block(full_table, columns, rows))
        parts.append("")
    parts.append("GO\n")

    parts.append("-- STEP 3 : RUN load procedures (Source -> PreStaging -> Staging -> DWH)")
    for title, logical, procs in LOAD_PROC_ORDER:
        parts.append(f"-- ---- {title} ----")
        parts.append(f"USE [{db_of(logical)}];")
        parts.append("GO")
        for p in procs:
            parts.append(f"EXEC {p};")
        parts.append("GO\n")

    parts.append("PRINT 'Synthetic test data loaded through all 4 layers.';")
    parts.append("GO")

    path = os.path.join(out_dir, "insert_all_source_testdata.sql")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    log.info(f"[agent_4] wrote {os.path.basename(path)}")
    return path


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def generate():
    """Generate the test-data INSERT scripts and return the list of paths."""
    base.banner("STEP 4  -  AI Agent: Generate Test Data + INSERT Scripts")
    print(base.ai_status())

    dataset = _dataset()

    # optional AI positive rows for the two FK-free tables
    extra_branches = _maybe_ai_extra("dbo.SRC_Branches", dataset[0][2], 6,
                                     "BranchID", "BranchCode", "BR")
    if extra_branches:
        dataset[0][3].extend(extra_branches)
    extra_customers = _maybe_ai_extra("dbo.SRC_Customers", dataset[1][2], 7,
                                      "CustomerID", "CustomerCode", "CU")
    if extra_customers:
        dataset[1][3].extend(extra_customers)

    out_dir = base.ensure_dir(base.TESTDATA_DIR)
    per_table = _write_per_table(out_dir, dataset)
    combined = _write_combined(out_dir, dataset)

    total = sum(len(rows) for _, _, _, rows in dataset)
    neg = sum(1 for _, _, _, rows in dataset for r in rows
              if str(r.get("_note", "")).startswith("NEGATIVE"))
    print(f"\n{total} rows ({neg} negative/edge) written to:\n  {out_dir}")
    for p in per_table + [combined]:
        print(f"  - {os.path.basename(p)}")
    print("\nThese scripts are NOT executed automatically. To load them, run:")
    print(f"  sqlcmd -S <server> -E -C -i \"{combined}\"")
    log.info(f"[agent_4] test data generated ({total} rows, {neg} negative)")
    return per_table + [combined]


if __name__ == "__main__":
    generate()
