"""
agents/agent_3_generate_code.py   -   STEP 3
============================================
AI Agent: generate runnable pytest CODE from the test cases produced in step 2.

Each test case's "Suggested Validation" column tells us which reusable function
in `validations/validations.py` proves it. This agent groups the test cases by
layer + table and emits one pytest file per table that calls those validations -
exactly the same pattern as the curated files in tests/ (see
tests/SourceToPreStaging/test_SRCPS_Accounts.py).

Generated files land in  agents/generated_tests/  (NOT tests/), so:
  * the curated suite is never overwritten, and
  * pytest's default `testpaths = tests` will not auto-collect them
    (run them explicitly:  pytest agents/generated_tests).

The code emitter is deterministic (always valid Python). When an
ANTHROPIC_API_KEY is present, Claude writes a richer module docstring; the test
logic itself is always template-generated so it is guaranteed to run.

Run:
    python -m agents.agent_3_generate_code
Output:
    agents/generated_tests/test_gen_<CODE>_<Table>.py  (+ __init__.py, README)
"""

import os

import openpyxl

from utilities.logger import get_logger
from agents import base

log = get_logger()

LAYER_CODE = {
    "SourceToPreStaging": "SRCPS",
    "PreStagingToStaging": "PSSTG",
    "StagingToDWH": "STGDW",
}
LAYER_MARKER = {
    "SourceToPreStaging": "source_to_prestaging",
    "PreStagingToStaging": "prestaging_to_staging",
    "StagingToDWH": "staging_to_dwh",
}

# validation -> (pytest method name, [markers that ARE declared in pytest.ini])
# NOTE: data_integrity / transformation have no dedicated declared marker, so we
# use the declared "transformation" group marker (pytest.ini has --strict-markers).
VALIDATION_META = {
    "Metadata_Validation":      ("test_metadata",       ["metadata_check", "basic"]),
    "Count_Validation":         ("test_count",          ["count_check", "basic"]),
    "Duplicate_Validation":     ("test_duplicates",     ["duplicate_check", "basic"]),
    "Null_Validation":          ("test_nulls",          ["null_check", "basic"]),
    "Constraint_Validation":    ("test_constraints",    ["constraint_check", "basic"]),
    "direct_move_Validation":   ("test_direct_move",    ["direct_move_check", "datamove"]),
    "data_integrity_Validation": ("test_data_integrity", ["transformation"]),
    "Transformation_Validation": ("test_transformation", ["transformation"]),
}
TABLE_MARKERS = {"Accounts", "Branches", "Customers", "Transactions"}


def _read_cases(xlsx_path):
    """Read the test-cases workbook into a list of dicts (one per row)."""
    wb = openpyxl.load_workbook(xlsx_path)
    cases = []
    for sheet in wb.sheetnames:
        ws = wb[sheet]
        headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
        for r in range(2, ws.max_row + 1):
            row = {headers[c - 1]: ws.cell(r, c).value
                   for c in range(1, ws.max_column + 1)}
            if row.get("TestCaseID"):
                cases.append(row)
    return cases


def _module_docstring(layer, table, tcids):
    """Deterministic docstring; optionally AI-polished into a clearer summary."""
    base_doc = (
        f"AUTO-GENERATED by agents/agent_3_generate_code.py - do not hand-edit.\n"
        f"Layer: {layer}  |  Table: {table}\n"
        f"Covers test cases: {', '.join(tcids)}\n"
        f"Each method asserts on a reusable check in validations/validations.py."
    )
    if not base.have_api_key():
        return base_doc
    try:
        system = ("Write a concise 2-3 sentence module docstring for an "
                  "auto-generated ETL pytest file. Be factual, no fluff.")
        user = (f"Layer {layer}, table {table}. It runs these validations for "
                f"the movement and asserts each passes. Keep the header lines.")
        polished = base.ask_claude(system, user, max_tokens=400)
        return base_doc + "\n\n" + polished.strip()
    except Exception as exc:
        log.warning(f"[agent_3] AI docstring skipped ({exc})")
        return base_doc


def _emit_file(layer, table, cases):
    """Build the Python source for one (layer, table) test file."""
    # dedupe by validation (each whole-table check runs once); keep TestCaseIDs
    seen = {}
    tcids = []
    for c in cases:
        val = c.get("Suggested Validation")
        tcids.append(str(c.get("TestCaseID")))
        if val in VALIDATION_META and val not in seen:
            seen[val] = c

    class_name = f"TestGen{table}{LAYER_CODE[layer]}"
    table_marker = table.lower() if table in TABLE_MARKERS else None

    lines = []
    lines.append('"""')
    lines.append(_module_docstring(layer, table, tcids))
    lines.append('"""')
    lines.append("")
    lines.append("import pytest")
    lines.append("from validations import validations as v")
    lines.append("")
    lines.append(f'LAYER = "{layer}"')
    lines.append(f'TABLE = "{table}"')
    lines.append("")
    lines.append("")
    lines.append(f"@pytest.mark.{LAYER_MARKER[layer]}")
    if table_marker:
        lines.append(f"@pytest.mark.{table_marker}")
    lines.append(f"class {class_name}:")
    lines.append(f'    """Generated checks for {layer} / {table}."""')
    lines.append("")

    for val, case in seen.items():
        method, markers = VALIDATION_META[val]
        desc = str(case.get("Description", "")).replace('"', "'")
        tcid = case.get("TestCaseID")
        for m in markers:
            lines.append(f"    @pytest.mark.{m}")
        lines.append(f"    def {method}(self):")
        lines.append(f'        """{tcid}: {desc}"""')
        lines.append(f"        assert v.{val}(LAYER, TABLE)")
        lines.append("")

    return class_name, "\n".join(lines).rstrip() + "\n"


def _write_support_files(out_dir):
    """Create __init__.py + a README so the folder is clearly separate."""
    init_path = os.path.join(out_dir, "__init__.py")
    with open(init_path, "w", encoding="utf-8") as f:
        f.write('"""AUTO-GENERATED pytest files (agent_3). Regenerate; do not '
                'hand-edit."""\n')
    readme = os.path.join(out_dir, "README.md")
    with open(readme, "w", encoding="utf-8") as f:
        f.write(
            "# Generated tests\n\n"
            "These pytest files are produced by "
            "`agents/agent_3_generate_code.py` from the test-cases workbook.\n\n"
            "They are **not** collected by the default `pytest` run "
            "(`testpaths = tests`). Run them explicitly:\n\n"
            "```bash\n"
            "pytest agents/generated_tests\n"
            "```\n\n"
            "Every method calls a reusable check in "
            "`validations/validations.py`. Regenerate rather than hand-editing.\n"
        )


def generate(xlsx_path=None):
    """Generate pytest files from the newest (or given) TestCases workbook."""
    base.banner("STEP 3  -  AI Agent: Generate Test Code")
    print(base.ai_status())

    xlsx_path = xlsx_path or base.latest_output("TestCases_")
    if not xlsx_path or not os.path.exists(xlsx_path):
        raise FileNotFoundError(
            "No TestCases_*.xlsx found in agents/output/. "
            "Run agent_2_test_cases first (python -m agents.agent_2_test_cases)."
        )
    print(f"Reading test cases from:\n  {xlsx_path}")

    cases = _read_cases(xlsx_path)
    out_dir = base.ensure_dir(base.GENERATED_TESTS_DIR)

    # group by (layer, table)
    groups = {}
    for c in cases:
        groups.setdefault((c["Layer"], c["Table"]), []).append(c)

    written = []
    for (layer, table), group in sorted(groups.items()):
        _, source = _emit_file(layer, table, group)
        fname = f"test_gen_{LAYER_CODE[layer]}_{table}.py"
        path = os.path.join(out_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(source)
        written.append(path)
        log.info(f"[agent_3] wrote {fname}")

    _write_support_files(out_dir)

    print(f"\n{len(written)} test file(s) written to:\n  {out_dir}")
    for p in written:
        print(f"  - {os.path.basename(p)}")
    print("\nRun them with:  pytest agents/generated_tests")
    log.info(f"[agent_3] generated {len(written)} test files")
    return written


if __name__ == "__main__":
    generate()
