name: Banking AI ETL Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:

    runs-on:
      - self-hosted
      - Windows
      - X64

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Secrets
        shell: pwsh
        run: |
          if ($env:EMAIL_APP_PASSWORD) {
            Write-Host "EMAIL_APP_PASSWORD FOUND"
          } else {
            Write-Host "EMAIL_APP_PASSWORD NOT FOUND"
          }

          if ($env:EMAIL_SENDER) {
            Write-Host "EMAIL_SENDER FOUND"
          } else {
            Write-Host "EMAIL_SENDER NOT FOUND"
          }

          if ($env:EMAIL_RECEIVER) {
            Write-Host "EMAIL_RECEIVER FOUND"
          } else {
            Write-Host "EMAIL_RECEIVER NOT FOUND"
          }

      - name: Run PyTest
        run: |
          pytest

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: Reports/